---
title: "Data Importt"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
```
after importing that data, we should clean up the names!
 ## Alright, let's look at the data
 
 printing in the console
```{r}

litters_df
```
  other ways to look at the data
```{r}
head(litters_df)
tail(litters_df)
```
  
```{r}
skimr::skim(litters_df)
```

## options to read_csv

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv", skip = 10, col_names = FALSE)
```

another thing to look at
```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv", na = c("", "NA", ".", 999))
```

## other files formats

read in an excel file.

```{r}
mlb_df = read_excel("./data_import_examples/mlb11.xlsx")
mlb_df
```

read in a SAS file.

```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
pulse_df
```

