---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS litters data
```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df
litters_df = janitor:: clean_names(litters_df)
```


## select

choose some columns and not others

```{r}
 select(litters_df, group,litter_number )
```

```{r}
select(litters_df, group:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

renaming columns...

```{r}
select(litters_df, GROUP = group, LITTER_number = litter_number)
```

```{r}
rename(litters_df,GROUP = group, LITTER_number = litter_number)
```

## Filter functions

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```
```{r}
filter(litters_df, gd_of_birth == 20, gd0_weight > 22)
```

what about character variables, and using the statement either or?

```{r}
filter(litters_df, group %in% c("Con7","Mod8"))
```

## mutate

```{r}
mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight, 
  group = str_to_lower(group)
  )
```

## Arrange

```{r}
arrange(litters_df, pups_born_alive)
```

